### ISSUE TITLE
Cannot update file metadata

### ISSUE THREAD

**Issue by FHowington** [googlearchive/PyDrive#101]
I am attempting to update the metadata of a file for which I have the fileID. My code is identical to that in the documentation:

```python
                f = drive.CreateFile({'id': filesContained['id']})
                f['title'] = filename
                print(f['title'])
                f.Upload()
                print(f['title'])
```
where the filesContained['id'] is the correct ID, as I have verified.
When I execute this code (in the context of my program), it will print the desired name of my file, but following the upload, the second print statement prints the original name of the file, and indeed the file is seen to not have its title changed in the google drive. What am I doing wrong?

**Comment by RNabel** [comment]
Thank you for reporting this. Have you checked whether the file's name is changed on Google Drive? The fact that the `title` value is reset would make some sense if the change was rejected for some reason. Are any errors raised?

If changes are successful remotely and you need a quick fix, you can try the code below:
```python
f = drive.CreateFile({'id': filesContained['id']})
f.FetchMetadata()
print(f['title'])
```

**Comment by fredfredhotdog** [comment]
Thanks for getting back to me. 

There are no errors raised, and the title of the file is not changed remotely. I made a cursory attempt to debug this problem, and found that the title is set correctly when I output it from within the Update function, but when printing the title from within the _FilesPatch function (which Update is calling) it has reverted to the value of the remote title.

**Comment by Adarsh-Shrivastava-001** [comment]
I am facing the same trouble

**Comment by mdmmn378** [comment]
Facing the same problem. Files get updated but their names remain the same.

**Comment by swearingbird** [comment]
I found a fix to this issue, first run a request to the file object, then make the changes.
```
f = drive.CreateFile({'id': filesContained['id']})  
f_old_title = f['title']
f['title'] = 'New Title'
f.Upload()
```

**Comment by abubelinha** [comment]
I agree with @swearingbird method (tried on Python 3.8, Windows 7, I could rename files and folders).
For some reason, the assignation of a new value to `f['title']` only works if its old value has been previously read.

Also, @RNabel `f.FetchMetadata()` code [above](https://github.com/googleworkspace/PyDrive/issues/101#issuecomment-306538993) raises an error, as reported in PyDrive2 fork issues #[91](https://github.com/iterative/PyDrive2/issues/91#issuecomment-787007425) and #[103](https://github.com/iterative/PyDrive2/issues/103)
